server:
    port: 8090
spring:
    security:
        oauth2:
            client:
                registration:
                    provider-me:
                        client-id: provider-me-server
                        client-secret: Tcg2812KVyWlwSIBDSldruSGDWzuSfz0
                        scope:
                            - openid
                            - profile
                            - roles
                        authorization-grant-type: authorization_code
                        redirect-uri: http://localhost:8090/login/oauth2/code/provider-me-server
                provider:
                    provider-me:
                        issuer-uri: http://localhost:9000/realms/provider-me